name: flutter_auth_seed
description: A phone authentication tutorial.

version: 1.2.0

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: "^3.2.2"
  firebase_auth: "^0.6.2+1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/glogo.png
